name: hello-world
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Сборка приложения
        run: make setup

      - name: Исполнение автотестов
        run: make test

      - name: Проверка чистоты кода
        run: make lint
